### ISSUE TITLE
Add inflation support [streams]

### ISSUE THREAD

**Issue by krisppurg** [guzba/zippy#15]
Since `zip` and this library doesn't support reusing the same z_stream context for multiple messages.

In my own discord library, I would like to implement some transport compression which neither zip or zippy have this functionality of creating a zlib inflation context to run chunks through. (https://discord.com/developers/docs/topics/gateway#transport-compression-transport-compression-example)

**Comment by krisppurg** [comment]
any news?

**Comment by guzba** [comment]
Hello, sorry I did not reply here before. It appears from glancing at the docs that you should be able to just call `uncompress` from zippy on each zlib chunk from Discord. Looking now, it also appears you've maybe got it working: https://github.com/krisppurg/dimscord/blob/ac2c7a04538207400efd526a1214afc794bff9a3/dimscord/gateway.nim#L452

Let me know if this is working or if there's still trouble.

**Comment by krisppurg** [comment]
That is there for a placeholder (it's temporary). And the commented code below the line is where I try to attempt to make it work using the example code on the docs as a reference. In other words the line you gave me is only for payload type compression, but I'm trying to implement zlib stream compression. The line won't work for zlib stream type compression, but rather on payload compression.

**Comment by guzba** [comment]
Ah ok, I understand what's up here. Hm, the issue here is it requires me to implement a zippy stream api, and also implement it exactly the same way as zlib does to be compatible. That may be the best way, who knows, I have not given it any thought. Will keep this issue open for future updates to this.

**Comment by krisppurg** [comment]
> Ah ok, I understand what's up here. Hm, the issue here is it requires me to implement a zippy stream api, and also implement it exactly the same way as zlib does to be compatible. That may be the best way, who knows, I have not given it any thought. Will keep this issue open for future updates to this.

any updates?

**Comment by guzba** [comment]
Hello, sorry to say, no I don't have any update. I have no need for this myself and would basically only be writing it to enable Discord stream compression. Which is cool but not exactly a huge deal. Given all the other things I'm working on, this is unlikely to get worked on any time soon so I'm going to close this issue.
