### ISSUE TITLE
Reading gzipped file without loading it into memory

### ISSUE THREAD

**Issue by telatin** [guzba/zippy#27]
Hi there,
thanks for this library!

At the moment I would be particularly interested in reading "gzipped" files but I didn't find the corresponding documentation. In particular, I need to read large files that would not fit in memory, either as streams or line by line.

Could you please help me with this?
Thank you very much

Andrea

**Comment by guzba** [comment]
Hello. Currently, Zippy operates on data entirely in memory so working with data larger than will fit in memory is not yet possible. In the future I would like to support a streaming operation which would enable this, but it is not here today.

**Comment by telatin** [comment]
Cool thanks!
