### ISSUE TITLE
Many empty invalid data

### ISSUE THREAD

**Issue by gavr123456789** [guzba/zippy#34]
I tried to compress the folder in which there were files with the vin code, everything worked well. Then I was wondering how to go inside folders inside archives and I created the following hierarchy:  
![image](https://user-images.githubusercontent.com/30507409/137046016-acd2c3b1-4c60-41b6-9f45-3db756b4a50d.png)  
code:  
```nim
createTarball("../utils/testFolder", "examples.tar.gz")
var tarbol = Tarball()
tarbol.open("examples.tar.gz")
echo tarbol.contents
```
And I got this:  
![image](https://user-images.githubusercontent.com/30507409/137046094-344d9dce-e8d3-4c32-be5f-af3878798ec0.png)
The wall of invalid data, but there are some correct things, For example I see `key: "testFolder/sas"` 
[examples.tar.gz](https://github.com/guzba/zippy/files/7333788/examples.tar.gz)
  
OS: Arch, nim: 1.4.8

**Comment by guzba** [comment]
Closing for now but please do let me know if you see unexpected invalid data again. Certainly don't want Zippy ever returning junk data like that after all.
