### ISSUE TITLE
Tests fail on macOS

### ISSUE THREAD

**Issue by ynfle** [guzba/zippy#38]
Since 8c431841f3130ac3705d12cd90e18d5e2ffcf26e (product of `git bisect` and tested on my local Mac) `nimble test` fails at https://github.com/guzba/zippy/blob/419ebae29ba0cdc6471aa76fe2019016c4dad558/tests/test_ziparchives.nim#L13
and it affects the Nim CI as well.

**Comment by guzba** [comment]
tar on Mac seems to fail on a test file. I've disabled that part of the test on Mac since I'm not really out to test Mac + tar. Tagged 0.9.5
