### ISSUE TITLE
suggest to seperate tests and examples from lib

### ISSUE THREAD

**Issue by retsyo** [guzba/zippy#47]
when we use `nimble install zippy`, the message says `Downloading https://github.com/guzba/zippy using git`. the directory `tests` takes up 35.1M, so it takes a long time to clone; ok to be honest, I have a bad internet supplier, for most of the time I can't finish `git clone`. I have to download the zipped source, which will be success sometimes, then install by hand. As a result, it is pain for me to install nim's library.

So, I propose to seperate test and examples from zippy lib, as a result we can get a rapid installation of the lib.

thanks

**Comment by guzba** [comment]
Hello and thanks for the issue. I will not be moving examples or tests out of the repo. It is very important that GitHub Actions can run on PRs and ensure things are working. Keeping this lib working is fundamental and the testing is required for that. As for the examples, they are just some text files and take up no space.

I have updated the tests to use smaller files, reducing the download a bit.
