### ISSUE TITLE
createZipArchive as stream to avoid "out of memory"

### ISSUE THREAD

**Issue by ThomasTJdev** [guzba/zippy#49]
I'm really glad for this library in our ZIP-utils.

We have started to use the library to create ZIP archives, which works fine until the ZIP files are larger than the available memory. In those cases we are getting the "out of memory".

Are there any hacks to overcome this? Procedures for using a stream, adding individual files instead of directories, or is it there no solution to this yet?

**Comment by guzba** [comment]
Hello, thanks for the issue. I am not happy with how I implemented my first take at creating zip archives and I only keep it around for compatibility. I someday plan to do a better version but I do not know when I'll be getting to it.

**Comment by ThomasTJdev** [comment]
Thanks for the reply @guzba and all the great work you put into the library. I'll find another way to zipping large archives for now.
