### ISSUE TITLE
Feature: glob ignore/include

### ISSUE THREAD

**Issue by konsumer** [guzba/zippy#65]
It would be cool to be able to include/ignore files in `createZipArchive`/`addDir` with an optional glob-pattern:

Like this would include all top-level files in `myfiles/`, but exclude `.DS_Store` files:

```nim
createZipArchive("myfiles/*", "file.zip", ".DS_Store")
```

Or include all files in current directory recursively, except zip files:

```nim
createZipArchive("**/*", "file.zip", "*.zip")
```

If there is interest, I can PR for it.

**Comment by guzba** [comment]
Hi and thanks for suggestion. Creating zip archives needs to be redone and is much more complex to do correctly than reading. I do not want to make any changes or new promises around the current zip archive creation. Thanks for the offer though.
