### ISSUE TITLE
`nimPreviewHashFarm` breaks concatenation test

### ISSUE THREAD

**Issue by c-blake** [guzba/zippy#78]
The error more specifically is this one:
```
tests/test_ziparchives_read.nim(46, 5) `entry == entries[numEntries]`
```
I don't understand why zip file catenation would depend upon string hasher order, but it is one of a couple things holding up [activating `nimPreviewHashFarm` by default](https://github.com/nim-lang/Nim/pull/23779).  So, if you could look into it soon, that would be awesome.

**Comment by guzba** [comment]
The issue here is that the test assumed the `Table` order was stable, but really I should use `OrderedTable`. I'll have a fix for this tagged in a little bit.

**Comment by guzba** [comment]
Tagged in https://github.com/guzba/zippy/releases/tag/0.10.14

**Comment by c-blake** [comment]
Thanks, for the quick work, man, esp. for the rapid release tag.
