### ISSUE TITLE
100 character file name limit in tarballs

### ISSUE THREAD

**Issue by beef331** [guzba/zippy#9]
Currently tarballs cannot have more than 100 characters. Resulting in an error.

**Comment by guzba** [comment]
Longer file paths in tarballs should work now. Tagged in 0.6.2.

The standard ustar tar file format limits still apply: each path chunk must be < 100 characters and each prefix path to a file name must be < 155 characters.

Ex: a/b/c.txt
a, b, and c.txt must individually be < 100 characters long
a/b must be < 155 characters long
